codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "tests/"
  - "scripts/"
  - "infra/"
