import type { EntityTemplate, NamingPattern, VariableProperty } from "./types";

/**
 * Client-side preview of template instantiation (F3-2c).
 *
 * Mirrors the server semantics of POST /templates/{id}/instantiate for the
 * generation types that can be resolved locally (fixed / choice / range /
 * pattern / list / numbered naming). TABLE variables can't be rolled without
 * the backend and LLM variables are intentionally left unresolved — both are
 * surfaced as placeholders so the user sees what still needs generation.
 */

export interface VariablePreview {
  property_path: string;
  generation_type: VariableProperty["generation_type"];
  /** Resolved value for locally-resolvable types; null otherwise. */
  value: unknown;
  /** Human-readable note for unresolved values (table roll / llm hint). */
  note: string | null;
}

export interface TemplatePreview {
  name: string;
  variables: VariablePreview[];
}

function pick<T>(items: T[]): T | undefined {
  if (items.length === 0) return undefined;
  return items[Math.floor(Math.random() * items.length)];
}

function substitutePattern(
  pattern: string,
  naming: NamingPattern,
  instanceNumber: number,
): string {
  const adjective = pick(naming.adjectives ?? []) ?? "Mysterious";
  const noun = pick(naming.nouns ?? []) ?? "Stranger";
  return pattern
    .replaceAll("{adjective}", adjective)
    .replaceAll("{noun}", noun)
    .replaceAll("{number}", String(instanceNumber));
}

/** Preview the instance name (override wins, mirroring the server). */
export function previewInstanceName(
  template: EntityTemplate,
  overrideName?: string,
): string {
  if (overrideName?.trim()) return overrideName.trim();
  const naming = template.naming_pattern;
  const instanceNumber = (template.usage_count ?? 0) + 1;
  switch (naming.type) {
    case "pattern":
      return naming.pattern
        ? substitutePattern(naming.pattern, naming, instanceNumber)
        : `${template.name} (Instance)`;
    case "numbered":
      return `${template.name} ${instanceNumber}`;
    case "list":
      return pick(naming.name_list ?? []) ?? `${template.name} (Instance)`;
    default:
      return `${template.name} (Instance)`;
  }
}

/** Preview one variable property. */
export function previewVariable(
  vp: VariableProperty,
  template: EntityTemplate,
): VariablePreview {
  const instanceNumber = (template.usage_count ?? 0) + 1;
  const base = { property_path: vp.property_path, generation_type: vp.generation_type };
  switch (vp.generation_type) {
    case "fixed":
      return { ...base, value: vp.options[0] ?? null, note: null };
    case "choice":
      return { ...base, value: pick(vp.options) ?? null, note: null };
    case "range":
      if (vp.range_min == null || vp.range_max == null) {
        return { ...base, value: null, note: "range not configured" };
      }
      return {
        ...base,
        value: vp.range_min + Math.floor(Math.random() * (vp.range_max - vp.range_min + 1)),
        note: null,
      };
    case "pattern":
      return {
        ...base,
        value: vp.pattern ? substitutePattern(vp.pattern, template.naming_pattern, instanceNumber) : null,
        note: vp.pattern ? null : "pattern not configured",
      };
    case "table":
      return { ...base, value: null, note: "rolled on a random table at creation" };
    case "llm":
      return { ...base, value: null, note: vp.llm_hint ?? "generated by the LLM at creation" };
    default:
      return { ...base, value: null, note: null };
  }
}

/** Full local preview for the instantiator dialog. */
export function previewInstantiation(
  template: EntityTemplate,
  overrideName?: string,
): TemplatePreview {
  return {
    name: previewInstanceName(template, overrideName),
    variables: template.variable_properties.map((vp) => previewVariable(vp, template)),
  };
}
