# ruff: noqa: E402, F401
"""
Pydantic schemas for MONITOR Data Layer.

These schemas define the data contracts for all operations.
They are used for:
- Request/response validation
- API documentation generation
- Type safety across the codebase

SCHEMA CATEGORIES:
- base:        Base models, enums (CanonLevel, Authority, etc)
- universe:    Universe, Multiverse schemas
- entities:    EntityArchetype, EntityInstance, entity types
- facts:       Fact, Event, canon_level, authority
- scenes:      Scene, Turn, ProposedChange, Resolution
- memories:    CharacterMemory, importance, valence
- sources:     Source, Document, Snippet
- queries:     Search requests, filters, pagination
- composite:   ContextPackage, CanonizationResult

See: docs/architecture/VALIDATION_SCHEMAS.md for full schema definitions
"""

from monitor_data.schemas.base import (
    AltWorldType,
    Authority,
    AxiomAuthority,
    BaseResponse,
    CanonicalMetadata,
    CanonLevel,
    CombatSide,
    CombatStatus,
    DetailLevel,
    DialogueStatus,
    EmotionalRelationType,
    EntityClass,
    EntityType,
    ExtractionStatus,
    HistoricalEventScope,
    IngestionStatus,
    KnowledgeTreeType,
    LoreEventStatus,
    NarrativeSourceType,
    NarrativeStyle,
    PartyStatus,
    ProposalStatus,
    ProposalType,
    SceneStatus,
    SessionStatus,
    SourceCanonLevel,
    SourcePriority,
    SourceType,
    Speaker,
    StoryStatus,
    StoryType,
    TemporalMode,
)
from monitor_data.schemas.change_log import (
    ChangeLogEntry,
    ChangeLogFilter,
    ChangeLogListResponse,
    ChangeSubjectType,
    ChangeType,
)
from monitor_data.schemas.character_sheets import (
    ApplyXPRequest,
    CharacterSheetCreate,
    CharacterSheetFilter,
    CharacterSheetListResponse,
    CharacterSheetResponse,
    CharacterSheetUpdate,
    SetActiveSheetRequest,
    SheetHistoryEntry,
)
from monitor_data.schemas.deduplication import (
    DeduplicationApplyRequest,
    DeduplicationResult,
    DeduplicationStrategy,
    DuplicateCategory,
    DuplicateGroup,
    DuplicateItemRef,
)
from monitor_data.schemas.documents import (
    DocumentCreate,
    DocumentFilter,
    DocumentListResponse,
    DocumentResponse,
    DocumentUpdate,
    SnippetCreate,
    SnippetFilter,
    SnippetListResponse,
    SnippetResponse,
    SourceCreate,
    SourceFilter,
    SourceListResponse,
    SourceResponse,
    SourceUpdate,
)
from monitor_data.schemas.entity_templates import (
    DefaultPersonality,
    EntityTemplateCreate,
    EntityTemplateFilter,
    EntityTemplateListResponse,
    EntityTemplateResponse,
    EntityTemplateUpdate,
    GenerationType,
    InstantiateEntityRequest,
    NamingPattern,
    NamingType,
    StatGeneration,
    VariableProperty,
)

# from monitor_data.schemas.entities import *
# from monitor_data.schemas.scenes import *
from monitor_data.schemas.facts import (
    AxiomCreate,
    AxiomFilter,
    AxiomResponse,
    AxiomUpdate,
    EventCreate,
    EventFilter,
    EventResponse,
    FactCreate,
    FactFilter,
    FactResponse,
    FactType,
    FactUpdate,
)
from monitor_data.schemas.game_systems import (
    AbilityScoreGeneration,
    AbilityScoreMethod,
    AdvancementEntry,
    AdvancementSystem,
    AttributeDefinition,
    Background,
    CharacterCreationProcedure,
    CoreMechanic,
    CoreMechanicType,
    CreationStep,
    CreationStepType,
    GameRule,
    GameRuleType,
    GameSystemCreate,
    GameSystemListResponse,
    GameSystemResponse,
    GameSystemUpdate,
    ResourceDefinition,
    RuleOverrideCreate,
    RuleOverrideListResponse,
    RuleOverrideResponse,
    RuleOverrideScope,
    RuleOverrideUpdate,
    SkillDefinition,
    StartingPackage,
    SuccessType,
)
from monitor_data.schemas.generated_narratives import (
    GeneratedNarrativeCreate,
    GeneratedNarrativeFilter,
    GeneratedNarrativeListResponse,
    GeneratedNarrativeResponse,
    GeneratedNarrativeUpdate,
)
from monitor_data.schemas.gm_notes import (
    GmNoteResponse,
    GmNoteUpsert,
)
from monitor_data.schemas.ingestion_delta import (
    DeltaCategory,
    DeltaItem,
    IngestionDelta,
    IngestionDeltaApplyRequest,
)
from monitor_data.schemas.ingestion_jobs import (
    IngestionJobCreate,
    IngestionJobFilter,
    IngestionJobListResponse,
    IngestionJobResponse,
    IngestionJobUpdate,
    IngestionStage,
)
from monitor_data.schemas.knowledge_packs import (
    AppliedToEntry,
    ApplyKnowledgePackRequest,
    EmbeddedGameSystem,
    ExtractedAxiom,
    ExtractedEntityArchetype,
    ExtractedLoreFact,
    KnowledgePackCreate,
    KnowledgePackFilter,
    KnowledgePackListResponse,
    KnowledgePackResponse,
    KnowledgePackStatus,
    KnowledgePackType,
    KnowledgePackUpdate,
    PackApplySession,
    PackConflict,
    PackExportEnvelope,
)
from monitor_data.schemas.lore_events import (
    LoreEventCreate,
    LoreEventFilter,
    LoreEventListResponse,
    LoreEventResponse,
    LoreEventUpdate,
)
from monitor_data.schemas.memories import (
    MemoryCreate,
    MemoryEmbedRequest,
    MemoryEmbedResponse,
    MemoryFilter,
    MemoryListResponse,
    MemoryResponse,
    MemorySearchRequest,
    MemorySearchResponse,
    MemorySearchResult,
    MemoryUpdate,
)
from monitor_data.schemas.npc_dialogues import (
    AppendDialogueMessage,
    DialogueMessage,
    NPCDialogueCreate,
    NPCDialogueFilter,
    NPCDialogueListResponse,
    NPCDialogueResponse,
    NPCDialogueUpdate,
)
from monitor_data.schemas.npc_profiles import (
    BehavioralTrigger,
    CharacterPreference,
    EmotionalTendency,
    NPCProfileCreate,
    NPCProfileResponse,
    NPCProfileUpdate,
)
from monitor_data.schemas.party_inventory import (
    ActiveSplitsResponse,
    AddInventoryItemRequest,
    InventoryItem,
    ItemCategory,
    PartyInventoryCreate,
    PartyInventoryResponse,
    PartySplitCreate,
    PartySplitResponse,
    RemoveInventoryItemRequest,
    ResolvePartySplitRequest,
    SplitHistoryFilter,
    SplitHistoryResponse,
    SplitStatus,
    SubParty,
    TransferItemRequest,
    TransferSourceType,
    TransferTargetType,
    UpdateGoldRequest,
)
from monitor_data.schemas.play_sessions import (
    PlaySessionAddScene,
    PlaySessionCreate,
    PlaySessionFilter,
    PlaySessionListResponse,
    PlaySessionResponse,
    PlaySessionUpdate,
)
from monitor_data.schemas.random_tables import (
    RandomTableCreate,
    RandomTableEntry,
    RandomTableFilter,
    RandomTableListResponse,
    RandomTableResponse,
    RandomTableType,
    RandomTableUpdate,
)
from monitor_data.schemas.relationships import (
    Direction,
    EmotionalRelationshipCreate,
    EmotionalRelationshipFilter,
    EmotionalRelationshipListResponse,
    EmotionalRelationshipResponse,
    EmotionalRelationshipUpdate,
    RelationshipCreate,
    RelationshipFilter,
    RelationshipListResponse,
    RelationshipResponse,
    RelationshipType,
    RelationshipUpdate,
    StateTag,
    StateTagResponse,
    StateTagUpdate,
)
from monitor_data.schemas.resolutions import (
    ActionType,
    CardDraw,
    ContestedRoll,
    Effect,
    EffectType,
    Mechanics,
    Modifier,
    ResolutionCreate,
    ResolutionFilter,
    ResolutionListResponse,
    ResolutionResponse,
    ResolutionType,
    ResolutionUpdate,
    RollResult,
    SuccessLevel,
)
from monitor_data.schemas.universe import (
    MultiverseCreate,
    MultiverseFilter,
    MultiverseResponse,
    MultiverseUpdate,
    OmniverseCreate,
    OmniverseResponse,
    OmniverseUpdate,
    UniverseCreate,
    UniverseFilter,
    UniverseResponse,
    UniverseUpdate,
)
from monitor_data.schemas.vectors import (
    VALID_COLLECTIONS,
    CollectionInfo,
    CollectionInfoRequest,
    CollectionInfoResponse,
    EntityChunkPayload,
    KnowledgeChunkPayload,
    MemoryChunkPayload,
    SceneChunkPayload,
    ScoredVector,
    SnippetChunkPayload,
    VectorBatchUpsertRequest,
    VectorCollection,
    VectorDeleteByFilterRequest,
    VectorDeleteRequest,
    VectorDeleteResponse,
    VectorFilter,
    VectorPoint,
    VectorSearchRequest,
    VectorSearchResponse,
    VectorUpsertRequest,
    VectorUpsertResponse,
)
from monitor_data.schemas.working_state import (
    AddStatModification,
    AddTemporaryEffect,
    CharacterWorkingState,
    DurationType,
    InventoryChange,
    InventoryChangeType,
    StatModification,
    TemporaryEffect,
    WorkingStateCreate,
    WorkingStateFilter,
    WorkingStateListResponse,
    WorkingStateResponse,
    WorkingStateUpdate,
)

# from monitor_data.schemas.sources import *
# from monitor_data.schemas.queries import *
# from monitor_data.schemas.composite import *

__all__ = [
    # Base enums and models
    "CanonLevel",
    "SourceCanonLevel",
    "Authority",
    "AxiomAuthority",
    "EntityType",
    "EntityClass",
    "StoryType",
    "StoryStatus",
    "SceneStatus",
    "ProposalStatus",
    "ProposalType",
    "Speaker",
    "PartyStatus",
    "CombatStatus",
    "CombatSide",
    "DetailLevel",
    "AltWorldType",
    "TemporalMode",
    "EmotionalRelationType",
    "DialogueStatus",
    "NarrativeStyle",
    "ExtractionStatus",
    "IngestionStatus",
    "SessionStatus",
    "KnowledgeTreeType",
    "SourcePriority",
    "HistoricalEventScope",
    "LoreEventStatus",
    "SourceType",
    "NarrativeSourceType",
    "CanonicalMetadata",
    "BaseResponse",
    # Universe schemas
    "OmniverseCreate",
    "OmniverseUpdate",
    "OmniverseResponse",
    "MultiverseCreate",
    "MultiverseUpdate",
    "MultiverseResponse",
    "MultiverseFilter",
    "UniverseCreate",
    "UniverseUpdate",
    "UniverseResponse",
    "UniverseFilter",
    # Resolution schemas
    "ActionType",
    "ResolutionType",
    "SuccessLevel",
    "EffectType",
    "Modifier",
    "RollResult",
    "ContestedRoll",
    "CardDraw",
    "Mechanics",
    "Effect",
    "ResolutionCreate",
    "ResolutionUpdate",
    "ResolutionResponse",
    "ResolutionFilter",
    "ResolutionListResponse",
    # Relationship schemas
    "RelationshipType",
    "Direction",
    "StateTag",
    "RelationshipCreate",
    "RelationshipUpdate",
    "RelationshipResponse",
    "RelationshipFilter",
    "RelationshipListResponse",
    "StateTagUpdate",
    "StateTagResponse",
    "EmotionalRelationshipCreate",
    "EmotionalRelationshipUpdate",
    "EmotionalRelationshipResponse",
    "EmotionalRelationshipFilter",
    "EmotionalRelationshipListResponse",
    # Vector schemas
    "VectorCollection",
    "VALID_COLLECTIONS",
    "SceneChunkPayload",
    "MemoryChunkPayload",
    "SnippetChunkPayload",
    "EntityChunkPayload",
    "KnowledgeChunkPayload",
    "VectorPoint",
    "VectorUpsertRequest",
    "VectorBatchUpsertRequest",
    "VectorUpsertResponse",
    "VectorFilter",
    "VectorSearchRequest",
    "ScoredVector",
    "VectorSearchResponse",
    "VectorDeleteRequest",
    "VectorDeleteByFilterRequest",
    "VectorDeleteResponse",
    "CollectionInfo",
    "CollectionInfoRequest",
    "CollectionInfoResponse",
    # Memory schemas
    "MemoryCreate",
    "MemoryUpdate",
    "MemoryFilter",
    "MemoryResponse",
    "MemoryListResponse",
    "MemoryEmbedRequest",
    "MemoryEmbedResponse",
    "MemorySearchRequest",
    "MemorySearchResult",
    "MemorySearchResponse",
    # Party Inventory schemas
    "ItemCategory",
    "TransferSourceType",
    "TransferTargetType",
    "SplitStatus",
    "InventoryItem",
    "PartyInventoryCreate",
    "PartyInventoryResponse",
    "AddInventoryItemRequest",
    "RemoveInventoryItemRequest",
    "TransferItemRequest",
    "UpdateGoldRequest",
    "SubParty",
    "PartySplitCreate",
    "PartySplitResponse",
    "ResolvePartySplitRequest",
    "ActiveSplitsResponse",
    "SplitHistoryFilter",
    "SplitHistoryResponse",
    # Game Systems schemas
    "CoreMechanicType",
    "SuccessType",
    "RuleOverrideScope",
    "GameRuleType",
    "GameRule",
    "AbilityScoreMethod",
    "CreationStepType",
    "CoreMechanic",
    "AttributeDefinition",
    "SkillDefinition",
    "ResourceDefinition",
    "AbilityScoreGeneration",
    "Background",
    "StartingPackage",
    "AdvancementEntry",
    "AdvancementSystem",
    "CreationStep",
    "CharacterCreationProcedure",
    "GameSystemCreate",
    "GameSystemUpdate",
    "GameSystemResponse",
    "GameSystemListResponse",
    "RuleOverrideCreate",
    "RuleOverrideUpdate",
    "RuleOverrideResponse",
    "RuleOverrideListResponse",
    # Working State schemas
    "DurationType",
    "InventoryChangeType",
    "StatModification",
    "TemporaryEffect",
    "InventoryChange",
    "CharacterWorkingState",
    "WorkingStateCreate",
    "WorkingStateUpdate",
    "AddStatModification",
    "AddTemporaryEffect",
    "WorkingStateFilter",
    "WorkingStateResponse",
    "WorkingStateListResponse",
    # Document / ingestion schemas
    "SourceCreate",
    "SourceUpdate",
    "SourceResponse",
    "SourceFilter",
    "SourceListResponse",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentFilter",
    "DocumentListResponse",
    "SnippetCreate",
    "SnippetResponse",
    "SnippetFilter",
    "SnippetListResponse",
    # Character sheet schemas
    "SheetHistoryEntry",
    "CharacterSheetCreate",
    "CharacterSheetUpdate",
    "CharacterSheetResponse",
    "CharacterSheetFilter",
    "CharacterSheetListResponse",
    "SetActiveSheetRequest",
    "ApplyXPRequest",
    # Entity template schemas
    "GenerationType",
    "NamingType",
    "VariableProperty",
    "NamingPattern",
    "StatGeneration",
    "DefaultPersonality",
    "EntityTemplateCreate",
    "EntityTemplateUpdate",
    "EntityTemplateResponse",
    "EntityTemplateFilter",
    "EntityTemplateListResponse",
    "InstantiateEntityRequest",
    # NPC profile schemas
    "EmotionalTendency",
    "CharacterPreference",
    "BehavioralTrigger",
    "NPCProfileCreate",
    "NPCProfileUpdate",
    "NPCProfileResponse",
    # NPC dialogue schemas
    "DialogueMessage",
    "NPCDialogueCreate",
    "AppendDialogueMessage",
    "NPCDialogueUpdate",
    "NPCDialogueResponse",
    "NPCDialogueFilter",
    "NPCDialogueListResponse",
    # Play session schemas
    "PlaySessionCreate",
    "PlaySessionUpdate",
    "PlaySessionAddScene",
    "PlaySessionResponse",
    "PlaySessionFilter",
    "PlaySessionListResponse",
    # Generated narrative schemas
    "GeneratedNarrativeCreate",
    "GeneratedNarrativeUpdate",
    "GeneratedNarrativeResponse",
    "GeneratedNarrativeFilter",
    "GeneratedNarrativeListResponse",
    # Ingestion job schemas
    "IngestionStage",
    "IngestionJobCreate",
    "IngestionJobUpdate",
    "IngestionJobResponse",
    "IngestionJobFilter",
    "IngestionJobListResponse",
    # Ingestion delta schemas
    "DeltaCategory",
    "DeltaItem",
    "IngestionDelta",
    "IngestionDeltaApplyRequest",
    # Deduplication schemas
    "DuplicateCategory",
    "DuplicateGroup",
    "DuplicateItemRef",
    "DeduplicationApplyRequest",
    "DeduplicationResult",
    "DeduplicationStrategy",
    # Knowledge pack schemas
    "KnowledgePackStatus",
    "KnowledgePackType",
    "EmbeddedGameSystem",
    "ExtractedAxiom",
    "ExtractedEntityArchetype",
    "ExtractedLoreFact",
    "AppliedToEntry",
    "KnowledgePackCreate",
    "KnowledgePackUpdate",
    "KnowledgePackResponse",
    "KnowledgePackFilter",
    "KnowledgePackListResponse",
    "ApplyKnowledgePackRequest",
    "PackConflict",
    "PackApplySession",
    "PackExportEnvelope",
    # Lore event schemas
    "LoreEventCreate",
    "LoreEventUpdate",
    "LoreEventResponse",
    "LoreEventFilter",
    "LoreEventListResponse",
    # Random table schemas
    "RandomTableType",
    "RandomTableEntry",
    "RandomTableCreate",
    "RandomTableUpdate",
    "RandomTableResponse",
    "RandomTableFilter",
    "RandomTableListResponse",
    # Change log schemas
    "ChangeSubjectType",
    "ChangeType",
    "ChangeLogEntry",
    "ChangeLogFilter",
    "ChangeLogListResponse",
]

from monitor_data.schemas.webhooks import (
    CommitWebhookCreate,
    CommitWebhookResponse,
    CommitWebhookUpdate,
    WebhookDeliveryLog,
    WebhookDeliveryStatus,
    WebhookEventType,
)

__all__ += [
    "CommitWebhookCreate",
    "CommitWebhookResponse",
    "CommitWebhookUpdate",
    "WebhookDeliveryLog",
    "WebhookDeliveryStatus",
    "WebhookEventType",
]

# Agent response schemas (used by agents layer via instructor/DSPy)
from monitor_data.schemas.agent_responses import (
    CanonKeeperDecision,
    CanonKeeperVerdict,
    NarratorResponse,
    ProposedChangeRef,
    ResolverOutcome,
    ResolverSuccessLevel,
)

__all__ += [
    "CanonKeeperDecision",
    "CanonKeeperVerdict",
    "NarratorResponse",
    "ProposedChangeRef",
    "ResolverOutcome",
    "ResolverSuccessLevel",
]

from monitor_data.schemas.llm_config import (
    PROVIDER_BASE_URLS,
    EffectiveLLMConfig,
    LLMNodeAssignment,
    LLMProviderConfig,
    LLMProviderType,
    ModelParams,
    ModelRole,
)

__all__ += [
    "PROVIDER_BASE_URLS",
    "EffectiveLLMConfig",
    "LLMNodeAssignment",
    "LLMProviderConfig",
    "LLMProviderType",
    "ModelParams",
    "ModelRole",
]

from monitor_data.schemas.tag_pool import SEMANTIC_CATEGORIES, TagPool

__all__ += [
    "SEMANTIC_CATEGORIES",
    "TagPool",
]

from monitor_data.schemas.conversations import (
    AppendConversationTurn,
    ConversationMode,
    ConversationSessionCreate,
    ConversationSessionFilter,
    ConversationSessionListResponse,
    ConversationSessionResponse,
    ConversationSessionUpdate,
    ConversationStatus,
    ConversationTurn,
)
from monitor_data.schemas.gm_profiles import (
    GMProfileCreate,
    GMProfileFilter,
    GMProfileListResponse,
    GMProfileResponse,
    GMProfileUpdate,
)

__all__ += [
    "AppendConversationTurn",
    "ConversationMode",
    "ConversationSessionCreate",
    "ConversationSessionFilter",
    "ConversationSessionListResponse",
    "ConversationSessionResponse",
    "ConversationSessionUpdate",
    "ConversationStatus",
    "ConversationTurn",
]
__all__ += [
    "GMProfileCreate",
    "GMProfileUpdate",
    "GMProfileResponse",
    "GMProfileFilter",
    "GMProfileListResponse",
    # GM Notes (P2.3)
    "GmNoteUpsert",
    "GmNoteResponse",
]
