"""
Pydantic schemas for EntityTemplate operations.

LAYER: 1 (data-layer)
IMPORTS FROM: External libraries (pydantic, uuid, datetime) and base schemas
CALLED BY: mongodb_tools.py

EntityTemplates are NPC generation blueprints stored in MongoDB.
They enable the GM to create NPCs on the fly with consistent mechanics.

When a player approaches an unnamed guard, the system uses an EntityTemplate
to instantly stub out the guard (STUB detail level), then elaborates them
as the player interacts (SKETCHED → DETAILED → ELABORATED).

Templates support inheritance via parent_template_id:
  Humanoid → Soldier → City Guard → City Guard (Capital)
"""

from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any
from uuid import UUID

from pydantic import BaseModel, Field

from monitor_data.schemas.base import DetailLevel, EntityType


# =============================================================================
# ENUMS
# =============================================================================


class GenerationType(str, Enum):
    """How a variable property is generated."""

    FIXED = "fixed"  # Always the same value
    CHOICE = "choice"  # Random choice from options list
    RANGE = "range"  # Random integer in [min, max]
    PATTERN = "pattern"  # String pattern with substitutions
    TABLE = "table"  # Roll on a random_table
    LLM = "llm"  # Generated by LLM at instantiation time


class NamingType(str, Enum):
    """How a generated entity is named."""

    PATTERN = "pattern"  # e.g., "Guard #{number}"
    NUMBERED = "numbered"  # Guard 1, Guard 2, ...
    LIST = "list"  # Drawn from a name list
    LLM = "llm"  # LLM generates a contextual name
    USER = "user"  # User provides the name


# =============================================================================
# SUB-MODELS
# =============================================================================


class VariableProperty(BaseModel):
    """A property that varies between instantiations of this template."""

    property_path: str = Field(
        max_length=200,
        description="Dot-path to the property (e.g., 'stats.STR', 'properties.faction')",
    )
    generation_type: GenerationType
    options: List[Any] = Field(
        default_factory=list,
        description="For CHOICE: list of possible values",
    )
    range_min: Optional[int] = Field(None, description="For RANGE: minimum value")
    range_max: Optional[int] = Field(None, description="For RANGE: maximum value")
    pattern: Optional[str] = Field(None, max_length=500, description="For PATTERN: template string")
    table_id: Optional[UUID] = Field(
        None, description="For TABLE: references MongoDB random_tables collection"
    )
    llm_hint: Optional[str] = Field(
        None,
        max_length=500,
        description="For LLM: hint/instruction for what to generate",
    )


class NamingPattern(BaseModel):
    """How generated entity instances are named."""

    type: NamingType = Field(default=NamingType.LLM)
    pattern: Optional[str] = Field(
        None, max_length=200, description="For PATTERN: e.g., '{adjective} {noun}'"
    )
    adjectives: List[str] = Field(default_factory=list)
    nouns: List[str] = Field(default_factory=list)
    name_list: List[str] = Field(
        default_factory=list, description="For LIST: pool of names to draw from"
    )


class StatGeneration(BaseModel):
    """How stats are generated for this template."""

    method: str = Field(
        default="fixed",
        max_length=50,
        description="fixed | roll | point_buy | array | scaled",
    )
    formulas: Dict[str, str] = Field(
        default_factory=dict,
        description="Stat-to-formula map (e.g., {'HP': '2d8+CON'})",
    )
    constraints: Dict[str, Any] = Field(
        default_factory=dict,
        description="Min/max constraints per stat",
    )
    game_system_id: Optional[UUID] = Field(
        None, description="Which game system these stats are for"
    )


class DefaultPersonality(BaseModel):
    """Personality defaults for instances of this template."""

    trait_pool: List[str] = Field(
        default_factory=list,
        description="Pool of traits to draw from (e.g., ['gruff', 'loyal', 'suspicious'])",
    )
    fear_pool: List[str] = Field(default_factory=list)
    desire_pool: List[str] = Field(default_factory=list)
    speech_styles: List[str] = Field(default_factory=list, description="Possible speech patterns")
    default_disposition: Optional[str] = Field(
        None,
        max_length=50,
        description="Default disposition toward player (hostile/neutral/friendly)",
    )


# =============================================================================
# ENTITY TEMPLATE CRUD SCHEMAS
# =============================================================================


class EntityTemplateCreate(BaseModel):
    """Request to create an EntityTemplate."""

    universe_id: UUID
    name: str = Field(min_length=1, max_length=200, description="Template name")
    description: str = Field(default="", max_length=2000)
    entity_type: EntityType
    # Base properties applied to every instance
    base_properties: Dict[str, Any] = Field(
        default_factory=dict,
        description="Fixed properties on every instance (role, faction_kind, etc.)",
    )
    # Properties that vary per instance
    variable_properties: List[VariableProperty] = Field(
        default_factory=list,
        description="Properties generated fresh per instantiation",
    )
    # Naming
    naming_pattern: NamingPattern = Field(default_factory=NamingPattern)
    # Stat generation
    stat_generation: StatGeneration = Field(default_factory=StatGeneration)
    # Defaults
    default_state_tags: List[str] = Field(
        default_factory=list,
        description="State tags applied to every new instance",
    )
    default_detail_level: DetailLevel = Field(
        default=DetailLevel.STUB,
        description="Detail level for freshly generated instances",
    )
    default_personality: Optional[DefaultPersonality] = Field(
        None, description="Personality defaults for generated NPCs"
    )
    # Template inheritance
    parent_template_id: Optional[UUID] = Field(
        None,
        description="Inherit base_properties from this template (e.g., Soldier inherits from Humanoid)",
    )


class EntityTemplateUpdate(BaseModel):
    """Request to update an EntityTemplate."""

    name: Optional[str] = Field(None, min_length=1, max_length=200)
    description: Optional[str] = Field(None, max_length=2000)
    base_properties: Optional[Dict[str, Any]] = None
    variable_properties: Optional[List[VariableProperty]] = None
    naming_pattern: Optional[NamingPattern] = None
    stat_generation: Optional[StatGeneration] = None
    default_state_tags: Optional[List[str]] = None
    default_detail_level: Optional[DetailLevel] = None
    default_personality: Optional[DefaultPersonality] = None


class EntityTemplateResponse(BaseModel):
    """Response with EntityTemplate data."""

    template_id: UUID
    universe_id: UUID
    name: str
    description: str
    entity_type: EntityType
    base_properties: Dict[str, Any]
    variable_properties: List[VariableProperty]
    naming_pattern: NamingPattern
    stat_generation: StatGeneration
    default_state_tags: List[str]
    default_detail_level: DetailLevel
    default_personality: Optional[DefaultPersonality] = None
    parent_template_id: Optional[UUID] = None
    usage_count: int = 0
    created_at: datetime
    updated_at: Optional[datetime] = None

    model_config = {"from_attributes": True}


class EntityTemplateFilter(BaseModel):
    """Filter for listing entity templates."""

    universe_id: Optional[UUID] = None
    entity_type: Optional[EntityType] = None
    parent_template_id: Optional[UUID] = None
    limit: int = Field(default=50, ge=1, le=200)
    offset: int = Field(default=0, ge=0)


class EntityTemplateListResponse(BaseModel):
    """Response for list operations."""

    templates: List[EntityTemplateResponse]
    total: int
    limit: int
    offset: int


# =============================================================================
# INSTANTIATION REQUEST
# =============================================================================


class InstantiateEntityRequest(BaseModel):
    """Request to generate a new EntityInstance from a template.

    The template generates a stub entity. If provide_context is set,
    the LLM elaborates the instance for that specific narrative context.
    """

    template_id: UUID
    scene_id: Optional[UUID] = Field(None, description="Scene where this entity is being created")
    story_id: Optional[UUID] = None
    provide_context: Optional[str] = Field(
        None,
        max_length=1000,
        description="Contextual hint for LLM generation (e.g., 'a nervous innkeeper who suspects the party')",
    )
    override_name: Optional[str] = Field(
        None, max_length=200, description="Override the generated name"
    )
    override_properties: Optional[Dict[str, Any]] = Field(
        None, description="Override any generated properties"
    )
