name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for taking the time to report this bug!

  - type: dropdown
    id: layer
    attributes:
      label: Affected Layer
      description: Which layer of the architecture is affected?
      options:
        - Layer 1 - Data Layer (packages/data-layer)
        - Layer 2 - Agents (packages/agents)
        - Layer 3 - CLI (packages/cli)
        - Documentation
        - Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter input '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant error messages or logs
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04]
        - Python version: [e.g., 3.11.5]
        - Package versions: [run `pip list | grep monitor`]

  - type: input
    id: related_use_case
    attributes:
      label: Related Use Case (if any)
      description: If this bug relates to a specific use case
      placeholder: "DL-1"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
