# M-7: Edit Universe
# ==================

id: "M-7"
title: "Edit Universe"
category: "manage"
epic: 1
priority: "medium"
status: "todo"

summary: |
  Modify an existing Universe's metadata including name, genre, tone,
  tech level, and description. Validates changes and maintains edit history.

actor: "User"
trigger: "Universe -> Edit or Manage -> Universe -> Edit <UUID>"

flow:
  - "Retrieve current Universe data"
  - "Display current values"
  - "Allow editing: name, genre, tone, tech_level, description"
  - "Validate changes (same rules as creation)"
  - "Update Neo4j node"
  - "Confirm changes"

acceptance_criteria:
  - "neo4j_update_universe updates specified fields only"
  - "Unchanged fields retain original values"
  - "Name uniqueness still enforced within Multiverse"
  - "Genre, tone, tech_level validated against enums"
  - "updated_at timestamp set on modification"
  - "CLI supports interactive and flag-based editing"
  - "CanonKeeper authority required for write"

depends_on:
  - "DL-1"  # Universe/Multiverse CRUD
  - "M-6"   # View Universe

blocks: []

implementation:
  layer: 3

  files:
    modify:
      - "packages/cli/src/monitor_cli/commands/manage/universe.py"

  cli_commands:
    - command: "monitor manage universe edit <UUID>"
      description: "Interactive edit"
    - command: "monitor manage universe edit <UUID> --name 'New Name'"
      description: "Update specific field"
    - command: "monitor manage universe edit <UUID> --genre sci-fi --tone gritty"
      description: "Update multiple fields"

  database_operations:
    neo4j:
      - name: "neo4j_get_universe"
        authority: ["*"]
      - name: "neo4j_update_universe"
        authority: ["CanonKeeper"]
        cypher: |
          MATCH (u:Universe {id: $universe_id})
          SET u.name = COALESCE($name, u.name),
              u.description = COALESCE($description, u.description),
              u.genre = COALESCE($genre, u.genre),
              u.tone = COALESCE($tone, u.tone),
              u.tech_level = COALESCE($tech_level, u.tech_level),
              u.updated_at = datetime()
          RETURN u

  patterns:
    - "Use COALESCE for optional updates"
    - "Follow DL-1 update pattern"

  notes: |
    - Consider adding edit history/audit log
    - May want to warn if universe has active stories

testing:
  unit_tests:
    - "test_edit_universe_single_field: one field updates"
    - "test_edit_universe_multiple_fields: multiple fields update"
    - "test_edit_universe_no_change: unchanged fields preserved"
    - "test_edit_universe_not_found: 404 handled gracefully"
    - "test_edit_universe_invalid_genre: bad genre rejected"

  integration_tests:
    - "test_edit_universe_cli: CLI edit flow works"

  coverage_minimum: 80

github:
  labels:
    - "epic-1"
    - "manage"
    - "cli"

  milestone: "EPIC 1: World & Multiverse"

references:
  docs:
    - "docs/USE_CASES.md#m-7-edit-universe"

  code:
    - "packages/data-layer/src/monitor_data/tools/neo4j_tools.py"
