# P-5: Handle Dialogue
# ====================

id: "P-5"
title: "Handle Dialogue"
category: "play"
epic: 4
priority: "high"
status: "todo"

summary: |
  Process player dialogue with NPCs or environment. Loads NPC personality,
  memories, and facts to generate contextually appropriate responses.
  Creates memories for both PC and NPC.

actor: "User"
trigger: "User speaks in-character or to NPC"

flow:
  - "Identify speaker (PC) and target (NPC or narration)"
  - "IF targeting NPC:"
  - "  Load NPC personality, memories, facts"
  - "  Generate NPC response using context"
  - "  Create memory for NPC (what was said)"
  - "  May trigger: information exchange, relationship change"
  - "IF narration (speaking aloud):"
  - "  Record as turn"
  - "  Other entities may react"
  - "Return to P-3"

acceptance_criteria:
  - "NPC identified from dialogue target"
  - "NPC personality loaded for response generation"
  - "Semantic memory search retrieves relevant NPC memories"
  - "NPC response reflects personality, knowledge, relationships"
  - "Memory created for NPC about this conversation"
  - "Memory created for PC if significant information exchanged"
  - "Relationship changes proposed if applicable"
  - "Information revelation tracked"

depends_on:
  - "DL-2"  # Entity data
  - "DL-7"  # Memories
  - "DL-10" # Vector search
  - "P-3"   # Turn Loop

blocks: []

implementation:
  layer: 2  # Agents layer

  files:
    modify:
      - "packages/agents/src/monitor_agents/narrator.py"
      - "packages/agents/src/monitor_agents/memory_manager.py"

  database_operations:
    neo4j:
      - name: "neo4j_get_entity"
        authority: ["*"]
        purpose: "Get NPC data"
      - name: "neo4j_list_facts"
        authority: ["*"]
        purpose: "NPC known facts"
    mongodb:
      - name: "mongodb_get_memories"
        collection: "memories"
      - name: "mongodb_create_memory"
        collection: "memories"
    qdrant:
      - name: "qdrant_search_memories"
        collection: "memories"
        purpose: "Semantic memory recall"

  npc_response_flow: |
    async def generate_npc_response(
        npc_id: UUID,
        player_said: str,
        context: Context
    ) -> str:
        # 1. Get NPC personality and state
        npc = await neo4j_get_entity(npc_id)

        # 2. Get NPC's memories of this player/topic
        memories = await qdrant_search_memories(npc_id, player_said, limit=5)

        # 3. Get relevant facts NPC knows
        facts = await neo4j_list_facts(entity_id=npc_id, limit=10)

        # 4. Build prompt with NPC personality, knowledge, memories
        prompt = build_npc_prompt(npc, memories, facts, player_said)

        # 5. Generate response via LLM
        response = await llm_generate(prompt)

        # 6. Create memory for NPC about this conversation
        await mongodb_create_memory({
            "entity_id": npc_id,
            "text": f"Player said: {player_said}. I responded: {response}",
            "scene_id": context.scene_id,
            "importance": 0.6
        })

        return response

  npc_prompt_template: |
    You are {npc.name}, a {npc.properties.role} in {universe.name}.

    Personality: {npc.properties.personality}
    Current state: {npc.state_tags}

    You know these facts:
    {facts}

    You remember:
    {memories}

    The player says: "{player_said}"

    Respond in character, considering:
    - Your personality and current mood
    - What you know and remember
    - Your relationship with the speaker

  patterns:
    - "RAG for memory retrieval"
    - "Personality-driven generation"

  notes: |
    - NPC consistency is key
    - Consider mood modifiers
    - Track what information NPCs reveal

testing:
  unit_tests:
    - "test_dialogue_npc_identified: target parsed"
    - "test_npc_memories_retrieved: relevant memories found"
    - "test_npc_response_personality: response matches personality"
    - "test_memory_created: NPC memory stored"
    - "test_dialogue_narration: non-NPC speech handled"

  integration_tests:
    - "test_dialogue_full_flow: dialogue -> response -> memory"
    - "test_npc_information_tracking: info exchange tracked"

  coverage_minimum: 80

github:
  labels:
    - "epic-4"
    - "play"
    - "agents"
    - "priority-high"

  milestone: "EPIC 4: Autonomous GM"

references:
  docs:
    - "docs/USE_CASES.md#p-5-handle-dialogue"

  code:
    - "packages/agents/src/monitor_agents/narrator.py"
    - "packages/agents/src/monitor_agents/memory_manager.py"
